# Generated by Django 4.2.13 on 2024-05-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
